config/routes.rb
Rails.application.routes.draw do

  resources :tweets
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    validates :tweet, presence: true, length: { minimum: 5, maximum: 160 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
    private

	def sign_up_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def acount_update_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_current_user, only: [ :create, :new ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    
  end

  # GET /tweets/new
  def new
    @tweet = @current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = @current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :index, status: :created, location: @tweet }
      else
        format.html { redirect_to root_path, alert: "Tweet was not posted" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end

    def set_current_user
      @current_user = current_user
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  private
  def sign_up_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #     redirect_to new_user_path
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    <nav class="navbar is-info">
        <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-5">Twitter</h1>
            <% end %>

            <div class="navbar-burger burger" data-target="navbarExample">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navbarExample" class="navbar-menu">
            <div class="navbar-end">
                <div class="buttons has-addons">
                    <% if !user_signed_in? %>
                    <div class="navbar-item">
                        <p class="control">
                            <%= link_to 'Sign In', new_user_session_path, class: "button is-info is-inverted"%>
                        </p>
                    </div>
                    <div class="navbar-item">
                        <p class="control">
                            <%= link_to "Sign Up", new_user_registration_path, class: "button is-info is-inverted" %>
                        </p>
                    </div>
                    <% else %>
                    <div class="navbar-item">
                        <p class="control">
                            <%= link_to 'New Tweet', new_tweet_path, class: "button is-info is-inverted"%>
                        </p>
                    </div>
                    <div class="navbar-item">
                        <p class="control">
                            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "button is-info is-inverted" %>
                        </p>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </nav>

    <%= yield %>
</body>

</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </p>
        </figure>
        <div class="media-content">
            <%= render 'form' %>
        </div>
    </article>
    <% end %>

    <% @tweets.each do |tweet| %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong><%= tweet.user.name %></strong><br />
                    <small>@<%= tweet.user.username %></small><br />
                    <p><%= tweet.tweet %></p>
                </div>
                <nav class="level">
                    <div class="level-left is-mobile">
                        <%= link_to tweet, class:"level-item" do %>
                        <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to edit_tweet_path(tweet), class:"level-item" do %>
                        <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet" } do %>
                        <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                        <% end %>
                    </div>
                </nav>
            </div>
        </article>
    </div>
    <% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
<%= f.error_notification %>
<div class="field">
    <div class="control">
        <%= f.input :tweet, label: "Tweet about it", input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, placeholder: "Compose a new tweet..." %>
    </div>
</div>
<%= f.button :submit, class:"button is-info" %>
<% end %>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Trends</p>
        <a class="panel-block">
            Trend 1
        </a>
        <a class="panel-block">
            Trend 2
        </a>
        <a class="panel-block">
            Trend 3
        </a>
        <a class="panel-block">
            Trend 4
        </a>
        <a class="panel-block">
            Trend 5
        </a>
    </nav>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who to Follow</p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>John Smith</strong>
                            <small>@johnsmith</small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>John Smith</strong>
                            <small>@johnsmith</small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>John Smith</strong>
                            <small>@johnsmith</small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
    </nav>
</div>

app/views/tweets/edit.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">

            <div class="column is-4">
                <h2 class="title is-2">Edit Tweet</h2>
                <%= render 'form', tweet: @tweet %>

            </div>
        </div>
</section>

app/views/tweets/index.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
            <%= render 'trends' %>
            <%= render 'feed' %>
            <%= render 'who-to-follow' %>
        </div>
    </div>
</section>

app/views/tweets/new.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">

            <div class="column is-4">
                <h2 class="title is-2">New Tweet</h2>
                <%= render 'form', tweet: @tweet %>

            </div>
        </div>
</section>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<section class="section">
    <div class="container">
        <div class="columns is-centered">

            <div class="column is-4">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-64x64">
                                <img src="https://bulma.io/images/placeholders/64x64.png">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <strong><%= @tweet.user.name %></strong><br />
                                <small>@<%= @tweet.user.username %></small><br />
                                <p><%= @tweet.tweet %></p>
                                <%= link_to root_path, class:"level-item" do %>
                                <span class="icon-text">
                                    <span class="icon">
                                        <i class="fa fa-home"></i>
                                    </span>
                                    <span>Home</span>
                                </span>
                                <% end %>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</section>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>